export const SITE_CONTENT = {
  brand: {
    name: 'Blinkit Fresh',
    brandFirst: 'Blinkit',
    brandSecond: 'Fresh',
    tagline: '10-Minute Instant Grocery & Market',
    companyAffiliation: 'NovaTech Ltd.',
    defaultDailyAllowance: 150.00,
    currencySymbol: '$',
    cutoffTime: 'Instant 10-15 Min',
    deliveryWindow: '10-15 Mins Express Delivery',
  },

  navigation: {
    announcementBadge: '10-Min Flash Delivery',
    announcementSuffix: 'express delivery to your door • $150 daily corporate allowance active',
    searchPlaceholder: "Search 'Avocado', 'Milk', 'Organic Eggs', 'Blueberries', 'Matcha'...",
    addressPrefix: 'Delivering to',
    manageAddressesLink: 'Manage Delivery Addresses →',
    menu: [
      { label: 'Store Catalog', href: '/products' },
      { label: 'Categories', href: '/categories' },
      { label: 'Past Orders', href: '/orders' },
    ],
  },

  homePage: {
    eyebrowTag: 'Instant Grocery Allowance',
    heroSubtitle: 'daily credit allowance provided by NovaTech Ltd.',
    heroDescription: 'Shop fresh farm produce, organic dairy, gourmet snacks, and chef meals delivered to your desk or doorstep in 10-15 minutes.',
    cutoffLabel: 'Delivery Speed',
    arrivalLabel: 'Express Arrival',
    categoriesEyebrow: 'Explore Grocery Categories',
    showAllCategories: 'View All Categories',
    spotlightEyebrow: 'Fresh Farm Spotlight',
    viewFullMenu: 'Browse Full Store',
    popularMealsTitle: 'Popular Grocery & Fresh Items',
    exploreAll: 'Explore All Products',
    perksBadge: 'Corporate Benefits Active',
    perksTitle: '$150.00 Daily Grocery & Lunch Credit Auto-Applied',
    perksDescription: 'NovaTech employees receive $150.00 daily credit automatically applied at checkout for fresh produce, healthy snacks, cold juices, and meals.',
    perksCheckBalanceBtn: 'Check Credit Balance',
    perksBrowseCatalogBtn: 'Browse Full Market',
  },

  productsPage: {
    eyebrow: 'Full Market Catalog',
    title: 'Instant Grocery & Fresh Market',
    subtitle: 'Explore 40+ organic fruits, hydroponic veggies, artisan dairy, cold juices, and gourmet meals.',
    filtersTitle: 'Refine Market Search',
    resetBtn: 'Reset Filters',
    categoriesHeading: 'Departments',
    dietHeading: 'Dietary Preference',
    maxPriceHeading: 'Max Price',
    sortHeading: 'Sort Order',
    emptyTitle: 'No grocery items match your filter selection.',
    clearFiltersBtn: 'Reset All Filters',
  },

  productModal: {
    aboutEyebrow: 'Item Specifications',
    caloriesLabel: 'Calories',
    prepTimeLabel: 'Express ETA',
    dietLabel: 'Category',
    instructionsLabel: 'Delivery & Handling Notes (Optional)',
    instructionsPlaceholder: 'e.g. Leave at reception front desk...',
    addBtn: 'Add to Cart',
  },

  cart: {
    headerEyebrow: 'Blinkit Instant Checkout',
    headerTitle: 'Your Grocery Bag',
    emptyTitle: 'Your grocery bag is empty',
    emptyDesc: 'Explore today\'s fresh market items to use your $150.00 company daily credit.',
    promoPlaceholder: 'Promo code (e.g. BLINKIT20)',
    applyBtn: 'Apply Code',
    removeBtn: 'Remove',
    mealTotalLabel: 'Basket Total',
    creditLabel: 'NovaTech Corporate Credit',
    promoLabel: 'Promo Discount',
    taxDeliveryLabel: 'Taxes & Express Delivery',
    youPayLabel: 'You Pay',
    creditNotice: 'Only excess amounts beyond your $150 daily credit are charged to your personal card.',
    placeOrderBtn: 'Place Express Order',
    proceedToCheckoutBtn: 'Proceed to Checkout',
    tipEyebrow: 'Express Courier Tip',
    tipDesc: '100% of tips go directly to your Blinkit express delivery partner.',
  },

  checkout: {
    eyebrow: '10-Minute Express Checkout',
    title: 'Finalize Grocery Order',
    step1Title: '1. Select Delivery Destination',
    step2Title: '2. Express Delivery Time Window',
    step3Title: '3. Payment Option Simulation',
    upiLabel: 'Enter your UPI VPA Handle',
    simNotice: 'Simulated payment transaction. No actual credit card charge occurs.',
    submitBtn: 'Place Express Order',
    submittingBtn: 'Processing Delivery...',
  },

  orderSuccess: {
    confirmedBadge: 'Order Confirmed',
    headline: 'Your Blinkit Order is on its Way!',
    subtitle: 'Blinkit dark store courier is packing your fresh groceries for 10-minute dispatch.',
    arrivalLabel: 'Guaranteed Express Delivery',
    stepperEyebrow: 'Live Order Dispatch Stepper',
    riderTitle: 'Blinkit Rider Partner',
    riderSub: 'Express Courier Unit',
    deliveringTo: 'Delivering To',
    receiptTitle: 'Itemized Digital Receipt',
    subtotalLabel: 'Basket Subtotal',
    creditLabel: 'NovaTech Corporate Credit',
    taxDeliveryLabel: 'Taxes & Delivery',
    totalPaidLabel: 'Total Paid',
    homeBtn: 'Return to Store',
    ordersBtn: 'View Order History',
  },

  footer: {
    guarantees: [
      {
        title: '10-15 Min Express Delivery',
        description: 'Dark store proximity ensures ultra-fast fulfillment',
      },
      {
        title: 'Farm Fresh Quality',
        description: 'Directly sourced organic veggies & fresh dairy',
      },
      {
        title: 'Daily Allowance Covered',
        description: 'Auto-applied $150 daily corporate allowance',
      },
      {
        title: 'Best Price Guarantee',
        description: 'Unmatched value across 40+ fresh items',
      },
    ],
    bio: 'Blinkit Fresh powers instant 10-minute grocery and gourmet meal delivery for office teams and homes, integrated directly with daily corporate allowance benefits.',
    categoriesTitle: 'Departments',
    accountTitle: 'Corporate Portal',
    platformTitle: 'Blinkit Services',
    copyright: '© 2026 Blinkit Fresh Technologies Inc. All rights reserved.',
    footnote: 'Powered by Blinkit Express & NovaTech Integration',
  },

  actions: {
    addToLunch: 'Add to Bag',
    browseMenu: 'Browse Market',
    reorder: 'Reorder Item',
    viewReceipt: 'View Receipt',
    setActive: 'Set Active',
    activeLocation: 'Active Target',
    saveAddress: 'Save Address',
  },
};
