export const SITE_CONTENT = {
  brand: {
    name: 'DC Stores',
    brandFirst: 'DC',
    brandSecond: 'Stores',
    tagline: 'Aesthetic Tumblers, Stationery, Books & Gifts',
    location: 'Shajapur, Madhya Pradesh',
    currencySymbol: '₹',
    cutoffTime: 'Express 30-45 Mins',
    deliveryWindow: '30-45 Mins Delivery in Shajapur',
  },

  navigation: {
    announcementBadge: 'Shajapur Express',
    announcementSuffix: 'Delivering Tumblers, Books, Stationery & Gifts across Shajapur, MP • Free delivery over ₹499',
    searchPlaceholder: "Search 'Insulated Tumbler', 'Leather Journal', 'Bestsellers', 'Soy Candles'...",
    addressPrefix: 'Delivering to',
    manageAddressesLink: 'Manage Delivery Locations →',
    menu: [
      { label: 'All Products', href: '/products' },
      { label: 'Categories', href: '/categories' },
      { label: 'My Orders', href: '/orders' },
    ],
  },

  homePage: {
    eyebrowTag: 'DC Stores Shajapur',
    heroSubtitle: 'Aesthetic Tumblers, Premium Stationery, Books & Custom Gifts',
    heroDescription: 'Shop aesthetic insulated tumblers, handcrafted journals, bestselling novels, scented candles, and custom gift hampers with express local delivery in Shajapur.',
    cutoffLabel: 'Express Delivery',
    arrivalLabel: 'Est. Delivery Time',
    categoriesEyebrow: 'Explore Lifestyle Categories',
    showAllCategories: 'View All Departments',
    spotlightEyebrow: 'Featured New Arrivals',
    viewFullMenu: 'Browse Full Store',
    popularMealsTitle: 'Popular Products & Best Sellers',
    exploreAll: 'Explore All Items',
    perksBadge: 'Quality Guaranteed',
    perksTitle: 'Premium Aesthetic Goods Delivered Direct to Your Doorstep in Shajapur',
    perksDescription: 'Curated selection of high-grade stainless steel tumblers, leatherette planners, viral books, and luxury gift sets available for instant delivery across Shajapur, MP.',
    perksCheckBalanceBtn: 'View New Arrivals',
    perksBrowseCatalogBtn: 'Explore Whole Store',
  },

  productsPage: {
    eyebrow: 'Store Catalog',
    title: 'DC Stores Collection',
    subtitle: 'Explore aesthetic drinkware, premium stationery, books, and curated gift sets.',
    filtersTitle: 'Refine Search',
    resetBtn: 'Reset Filters',
    categoriesHeading: 'Departments',
    dietHeading: 'Category Type',
    maxPriceHeading: 'Max Price (₹)',
    sortHeading: 'Sort Order',
    emptyTitle: 'No items match your filter selection.',
    clearFiltersBtn: 'Reset All Filters',
  },

  productModal: {
    aboutEyebrow: 'Product Specifications',
    caloriesLabel: 'Material / Spec',
    prepTimeLabel: 'Express ETA',
    dietLabel: 'Department',
    instructionsLabel: 'Gift Message / Packing Notes (Optional)',
    instructionsPlaceholder: 'e.g. Include a birthday greeting card...',
    addBtn: 'Add to Bag',
  },

  cart: {
    headerEyebrow: 'DC Stores Express Checkout',
    headerTitle: 'Your Shopping Bag',
    emptyTitle: 'Your shopping bag is empty',
    emptyDesc: 'Explore our latest collection of aesthetic tumblers, stationery, books, and gifts.',
    promoPlaceholder: 'Promo code (e.g. SHAJAPUR10)',
    applyBtn: 'Apply',
    removeBtn: 'Remove',
    mealTotalLabel: 'Bag Subtotal',
    promoLabel: 'Promo Discount',
    taxDeliveryLabel: 'GST & Local Delivery',
    youPayLabel: 'Total Payable',
    creditNotice: '100% Secure Payment with Instant Shajapur Express Delivery.',
    placeOrderBtn: 'Place Order',
    proceedToCheckoutBtn: 'Proceed to Checkout',
    tipEyebrow: 'Delivery Rider Tip',
    tipDesc: '100% of tips go directly to your Shajapur express delivery partner.',
  },

  checkout: {
    eyebrow: 'Express Shajapur Checkout',
    title: 'Finalize Your Order',
    step1Title: '1. Select Delivery Address in Shajapur',
    step2Title: '2. Delivery Time Window',
    step3Title: '3. Payment Method Options',
    upiLabel: 'Enter your UPI VPA / Mobile Handle (Google Pay, PhonePe, Paytm)',
    simNotice: 'Simulated payment transaction. No real charge occurs.',
    submitBtn: 'Confirm & Place Order',
    submittingBtn: 'Placing Order...',
  },

  orderSuccess: {
    confirmedBadge: 'Order Confirmed',
    headline: 'Your DC Stores Order is Confirmed!',
    subtitle: 'DC Stores Shajapur warehouse is packing your items for 30-45 min express dispatch.',
    arrivalLabel: 'Guaranteed Local Delivery',
    stepperEyebrow: 'Live Order Status',
    riderTitle: 'DC Stores Partner',
    riderSub: 'Express Delivery Unit',
    deliveringTo: 'Delivering To',
    receiptTitle: 'Itemized Digital Receipt',
    subtotalLabel: 'Subtotal',
    taxDeliveryLabel: 'GST & Delivery',
    totalPaidLabel: 'Total Paid',
    homeBtn: 'Return to Store',
    ordersBtn: 'View My Orders',
  },

  footer: {
    guarantees: [
      {
        title: '30-45 Min Shajapur Delivery',
        description: 'Local store proximity ensures fast delivery across Shajapur',
      },
      {
        title: 'Premium Quality Guarantee',
        description: 'High-grade tumblers, authentic books, and fine stationery',
      },
      {
        title: 'Aesthetic Gift Wrapping',
        description: 'Free custom gift packaging available upon request',
      },
      {
        title: 'Best Local Prices',
        description: 'Unmatched value across all lifestyle and gift collections',
      },
    ],
    bio: 'DC Stores is Shajapur\'s premier online destination for aesthetic tumblers, stationery, books, curated hampers, and lifestyle essentials delivered to your doorstep.',
    categoriesTitle: 'Departments',
    accountTitle: 'Customer Account',
    platformTitle: 'DC Stores Info',
    copyright: '© 2026 DC Stores Shajapur. All rights reserved.',
    footnote: 'Serving Shajapur, Madhya Pradesh',
  },

  actions: {
    addToLunch: 'Add to Bag',
    browseMenu: 'Browse Catalog',
    reorder: 'Reorder Item',
    viewReceipt: 'View Receipt',
    setActive: 'Set Active',
    activeLocation: 'Active Address',
    saveAddress: 'Save Address',
  },
};
